<link href="<c:url value='/resources/css/bootstrap.css' />" rel="stylesheet"></link>
<link href="<c:url value='/resources/css/bootstrap-theme.css' />" rel="stylesheet"></link>
<script src="<c:url value='/resources/js/jquery-1.9.1.js' />" ></script>
<script src="<c:url value='/resources/js/bootstrap.js' />" ></script>
<script src="<c:url value='/resources/js/scriptCam/swfobject.js' />" ></script>
<script src="<c:url value='/resources/js/scriptCam/scriptcam.js' />" ></script>
<script src="<c:url value='/resources/js/systemJS.js' />" ></script>
<link href="<c:url value='/resources/css/systemStyle.css' />" rel="stylesheet"></link>
<script src="<c:url value='/resources/js/dynatable/jquery.dynatable.js' />" ></script>
<link href="<c:url value='/resources/css/dynatable/jquery.dynatable.css' />" rel="stylesheet"></link>
<script src="<c:url value='/resources/js/product.js' />" ></script>