package teste;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

public class TesteJson {

	public static void main(String[] args) {

JSONObject obj = new JSONObject();
		
		JSONArray list = new JSONArray();
		
		JSONObject j = new JSONObject();
		  j.put("first_name", "Airi");
		  j.put("last_name", "Satou");
		  j.put("position", "Accountant");
		  j.put("office", "Tokyo");
		  j.put("start_date", "28th Nov 08");
		  j.put("salary", "$162,700");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Angelica");
		  j.put("last_name", "Ramos");
		  j.put("position", "Chief Executive Officer (CEO)");
		  j.put("office", "London");
		  j.put("start_date", "9th Oct 09");
		  j.put("salary", "$1,200,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Ashton");
		  j.put("last_name", "Cox");
		  j.put("position", "Junior Technical Author");
		  j.put("office", "San Francisco");
		  j.put("start_date", "12th Jan 09");
		  j.put("salary", "$86,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Bradley");
		  j.put("last_name", "Greer");
		  j.put("position", "Software Engineer");
		  j.put("office", "London");
		  j.put("start_date", "13th Oct 12");
		  j.put("salary", "$132,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Brenden");
		  j.put("last_name", "Wagner");
		  j.put("position", "Software Engineer");
		  j.put("office", "San Francisco");
		  j.put("start_date", "7th Jun 11");
		  j.put("salary", "$206,850");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Brielle");
		  j.put("last_name", "Williamson");
		  j.put("position", "Integration Specialist");
		  j.put("office", "New York");
		  j.put("start_date", "2nd Dec 12");
		  j.put("salary", "$372,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Bruno");
		  j.put("last_name", "Nash");
		  j.put("position", "Software Engineer");
		  j.put("office", "London");
		  j.put("start_date", "3rd May 11");
		  j.put("salary", "$163,500");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Caesar");
		  j.put("last_name", "Vance");
		  j.put("position", "Pre-Sales Support");
		  j.put("office", "New York");
		  j.put("start_date", "12th Dec 11");
		  j.put("salary", "$106,450");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Cara");
		  j.put("last_name", "Stevens");
		  j.put("position", "Sales Assistant");
		  j.put("office", "New York");
		  j.put("start_date", "6th Dec 11");
		  j.put("salary", "$145,600");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Cedric");
		  j.put("last_name", "Kelly");
		  j.put("position", "Senior Javascript Developer");
		  j.put("office", "Edinburgh");
		  j.put("start_date", "29th Mar 12");
		  j.put("salary", "$433,060");
		list.add( j );
		
		j = new JSONObject();
		  j.put("first_name", "Airi2");
		  j.put("last_name", "Satou2");
		  j.put("position", "Accountant");
		  j.put("office", "Tokyo");
		  j.put("start_date", "28th Nov 08");
		  j.put("salary", "$162,700");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Angelica2");
		  j.put("last_name", "Ramos2");
		  j.put("position", "Chief Executive Officer (CEO)");
		  j.put("office", "London");
		  j.put("start_date", "9th Oct 09");
		  j.put("salary", "$1,200,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Ashton2");
		  j.put("last_name", "Cox2");
		  j.put("position", "Junior Technical Author");
		  j.put("office", "San Francisco");
		  j.put("start_date", "12th Jan 09");
		  j.put("salary", "$86,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Bradley2");
		  j.put("last_name", "Greer2");
		  j.put("position", "Software Engineer");
		  j.put("office", "London");
		  j.put("start_date", "13th Oct 12");
		  j.put("salary", "$132,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Brenden2");
		  j.put("last_name", "Wagner2");
		  j.put("position", "Software Engineer");
		  j.put("office", "San Francisco");
		  j.put("start_date", "7th Jun 11");
		  j.put("salary", "$206,850");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Brielle2");
		  j.put("last_name", "Williamson2");
		  j.put("position", "Integration Specialist");
		  j.put("office", "New York");
		  j.put("start_date", "2nd Dec 12");
		  j.put("salary", "$372,000");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Bruno2");
		  j.put("last_name", "Nash2");
		  j.put("position", "Software Engineer");
		  j.put("office", "London");
		  j.put("start_date", "3rd May 11");
		  j.put("salary", "$163,500");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Caesar2");
		  j.put("last_name", "Vance2");
		  j.put("position", "Pre-Sales Support");
		  j.put("office", "New York");
		  j.put("start_date", "12th Dec 11");
		  j.put("salary", "$106,450");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Cara2");
		  j.put("last_name", "Stevens2");
		  j.put("position", "Sales Assistant");
		  j.put("office", "New York");
		  j.put("start_date", "6th Dec 11");
		  j.put("salary", "$145,600");
		list.add( j );
		j = new JSONObject();
		  j.put("first_name", "Cedric2");
		  j.put("last_name", "Kelly2");
		  j.put("position", "Senior Javascript Developer");
		  j.put("office", "Edinburgh");
		  j.put("start_date", "29th Mar 12");
		  j.put("salary", "$433,060");
		list.add( j );
		
		obj.put("data", list);
		
		obj.put("recordsTotal", ""+list.size() );
		obj.put("recordsFiltered", ""+list.size() );
		obj.put("draw","1");

		System.out.print(obj.toJSONString());

		obj.toJSONString();

	}

}
